### PR TITLE
Add Galileo UEFI support

### PR DESCRIPTION
**Pull request by mlemay-intel**
This patch adds support for optionally building EFI binaries in addition to Multiboot ELF binaries.

### CODE REVIEW

**Comment by mlemay-intel** [comment]
What are your thoughts on this?  Are you still interested in having UEFI support in Contiki?

**Comment by jeez** [comment]
I don't see why not... @mlemay-intel can you please rebase this on top of the current x86 and push -f the branch so the PR is updated?

@ricardotk can you please test this today on your galileo ?


thanks!

**Comment by mlemay-intel** [comment]
I rebased.  Please let me know how the testing goes, @ricardotk.  Thanks.

**Comment by ricardotk** [comment]
It didn't work for me.

>[tk@valkyrie hello-world]$ make TARGET=galileo
>  CC        ../../platform/galileo/./newlib-syscalls.c
>  CC        hello-world.c
>  LD        hello-world.galileo
>  LD        hello-world.galileo.dll
>GenFw: ERROR 3000: Invalid
>  hello-world.galileo.dll bad symbol definition.
>GenFw: ERROR 3000: Invalid
>  hello-world.galileo.dll bad symbol definition.
>../../platform/galileo/Makefile.customrules-galileo:38: recipe for target 'hello-world.galileo.efi' failed
>make: *** [hello-world.galileo.efi] Error 2
>rm hello-world.galileo.dll hello-world.co

Do you have any idea what it might be? @mlemay-intel

**Comment by mlemay-intel** [comment]
Hmm, that's weird.  I've seen that problem in the past, but not recently.  I'll email you an EDK2 patch that will increase the diagnostic output from GenFw.

**Comment by mlemay-intel** [comment]
@ricardotk and I communicated over email to debug this, and we were able to resolve the issue by rebuilding newlib.  The UEFI patch changes some newlib build flags.  @ricardotk suggested adding a check in build_uefi.sh to make sure newlib is rebuilt.  However, the modified newlib flags take effect regardless of whether UEFI support is enabled, so anyone that builds newlib from a version of the code that includes the UEFI patches should not encounter this issue.  Thus, I propose merging the patches as-is.  Sound good?

**Comment by mlemay-intel** [comment]
Ping...

**Comment by jeez** [comment]
@aguedes Can you please review this so we move forward with it?

I remember you said a while ago you would have a look at it...

**Comment by aguedes** [comment]
When UEFI is enabled, does the command 'make debug' work normally?

**Comment by mlemay-intel** [comment]
I'm not too familiar with 'make debug', but I don't see why it would be affected.  The multiboot image still gets built, even with UEFI enabled.

**Comment by aguedes** [comment]
On 10/27/2015 02:59 PM, Michael LeMay wrote:
> I'm not too familiar with 'make debug', but I don't see why it would be
> affected. The multiboot image still gets built, even with UEFI enabled.

'make debug' is just a helper target we have which runs openocd and gdb, 
passing the right arguments to initiate a debugging section.

I'm now wondering if the debugging section doesn't go crazy since we are 
using the multiboot binary to the debugger, but the board is actually 
running the EFI binary. Could you check this please?

**Comment by jeez** [comment]
[**@mlemay-intel**](https://github.com/mlemay-intel) commented on [Oct 27, 2015, 3:00 PM GMT-2](https://github.com/otcshare/contiki-x86/pull/2#commitcomment-14017158 "2015-10-27T17:00:58Z - Replied by Github Comment Enhancer"):
> I'll move this over.

There is a slight chance -fno-unwind-tables will not remove anything else after -fno-asynchronous-unwind-tables is in use, btw.

**Comment by jeez** [comment]
[**@mlemay-intel**](https://github.com/mlemay-intel) commented on [Oct 27, 2015, 3:00 PM GMT-2](https://github.com/otcshare/contiki-x86/pull/2#commitcomment-14017137 "2015-10-27T17:00:24Z - Replied by Github Comment Enhancer"):
> I can move it over.

I'm actually unsure UEFI-based boot is something you get with the SoC. It looks like something you get with a platform.

**Comment by mlemay-intel** [comment]
Yes, you're right.  However, I think all the Quark X1000 platforms use UEFI, so I think the UEFI support should be associated with this SoC.

**Comment by mlemay-intel** [comment]
I don't have a Flyswatter adapter, so I'm unfortunately not able to test make debug.

**Comment by mlemay-intel** [comment]
I pushed a new version.

**Comment by aguedes** [comment]
The patches LGTM.

**Pull request merged**
