### PR TITLE
Streamline MMIO accesses in GPIO and I2C drivers

### PR DESCRIPTION
**Pull request by mlemay-intel**
This patch refactors the MMIO routines in the GPIO and I2C drivers to
eliminate the base_addr parameter that specifies the MMIO base
address.  Instead, just the MMIO routines themselves retrieve the base
address from the driver structure.

### CODE REVIEW

**Comment by mlemay-intel** [comment]
I'm working on rebasing my protection domain patches on our recent changes.  It's simpler for me to put the I2C and GPIO drivers in a protection domain if I can centralize the MMIO base address computation in just a couple of routines per driver.  I haven't tested the functionality of this patch, but it compiles fine with the gpio-interrupt and i2c-LSM9DS0 examples.

**Comment by mlemay-intel** [comment]
Any thoughts on this patch, @ricardotk?

**Comment by ricardotk** [comment]
I didn't have time to test its functionality yet, I'll try to do it today.

**Comment by ricardotk** [comment]
+2

**Comment by mlemay-intel** [comment]
Thanks, sorry for the delay in merging this.  My spam filter was catching GitHub notifications.  I'll merge this today.

**Pull request closed without merging**
